//
//  DetailsInteractor.swift
//  TentBearTask
//
//  Created by Nrmeen Tomoum on 09/01/2020.
//  Copyright (c) 2020 Nermeen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic
{
    func getUserInfo()
}

protocol DetailsDataStore
{
    var user: Home.Users.Response? { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore
{
    var user: Home.Users.Response?
    
    var presenter: DetailsPresentationLogic?
    var worker: DetailsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func getUserInfo()
    {
        if   let response = user
        {
            presenter?.presentUserInfo(response: response)
        }
    }
}
