//
//  DetailsPresenter.swift
//  TentBearTask
//
//  Created by Nrmeen Tomoum on 09/01/2020.
//  Copyright (c) 2020 Nermeen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic
{
    func presentUserInfo(response: Home.Users.Response)
}

class DetailsPresenter: DetailsPresentationLogic
{
  weak var viewController: DetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentUserInfo(response: Home.Users.Response)
  {
    viewController?.displayUserInfo(viewModel: response)
  }
}
