//
//  HomeInteractor.swift
//  TentBearTask
//
//  Created by Nrmeen Tomoum on 09/01/2020.
//  Copyright (c) 2020 Nermeen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func getListOfUsers()
}

protocol HomeDataStore
{
  //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func getListOfUsers()
  {
    worker = HomeWorker()
    self.presenter?.presentLoader()
    worker?.getListOfUsers(completionHandler: { (respond, errorCode) in
        self.presenter?.stopLoader()
        if let response = respond
                  {
                    self.presenter?.presentListOfUsers(response: response.data!)
                       }
                  else if let error = errorCode
                  {
                  //  self.presenter?.presentAlertMessage(message: (error.hashValue))
                  }
        
    })
    
//    let response = Home.Something.Response()
//    presenter?.presentSomething(response: response)
  }
}
