//
//  HomeViewController.swift
//  TentBearTask
//
//  Created by Nrmeen Tomoum on 09/01/2020.
//  Copyright (c) 2020 Nermeen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FCAlertView
import CoreData
protocol HomeDisplayLogic: class
{
    func displayListOfUsers(viewModel: [Home.Users.Response])
    func displayIndecator()
    func stopIndecator()
    func createAlert(title: String, subTitle: String)
}

class HomeViewController:  UITableViewController,HomeDisplayLogic
{
    
    var interactor: HomeBusinessLogic?
    var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
    var viewIndecator = loader ()
    var displayedUsers: [Home.Users.Response] = []
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = HomeInteractor()
        let presenter = HomePresenter()
        let router = HomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        getListOfUsers()
    }
    
    // MARK: Do something
    func createAlert(title: String, subTitle: String) {
        CAlert.createAlert(title: title, subTitle: subTitle,vc: self)
    }
    
    func displayIndecator()
    {
        viewIndecator.startIndecator(self.view)
    }
    func stopIndecator()
    {
        viewIndecator.stopIndecator(self.view)
    }
    //@IBOutlet weak var nameTextField: UITextField!
    
    func displayListOfUsers(viewModel: [Home.Users.Response]) {
        displayedUsers = viewModel
        var setOfUsersFromCD: [NSManagedObject] = []
        DBManger.fetchCD("User", dataRetrived: &setOfUsersFromCD)
        print(setOfUsersFromCD)
        tableView.reloadData()
    }
    
    func getListOfUsers()
    {
        interactor?.getListOfUsers()
    }
}

extension HomeViewController: FCAlertViewDelegate
{
    func fcAlertDoneButtonClicked(_ alertView: FCAlertView!) {
    }
}

extension HomeViewController
    
{
    // MARK: - Table view data source
    
    override func numberOfSections(in tableView: UITableView) -> Int
    {
        return 1
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
    {
        return displayedUsers.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
    {
        let displayedUser = displayedUsers[indexPath.row]
        var cell = tableView.dequeueReusableCell(withIdentifier: "OrderTableViewCell")
        if cell == nil {
            cell = UITableViewCell(style: .value1, reuseIdentifier: "OrderTableViewCell")
        }
        cell?.textLabel?.text = displayedUser.first_name
        cell?.detailTextLabel?.text = displayedUser.last_name
        return cell!
    }
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        router?.routeToDetails(segue: nil)
    }
}
